model_name: atss_retina
data:
  # train_annotation_path: 'D:/Documents/Academic/workspace/python_prj/now/Steel_defect/dataset/NEU-DET_COCO/annotations/train.json'
  # val_annotation_path: 'D:/Documents/Academic/workspace/python_prj/now/Steel_defect/dataset/NEU-DET_COCO/annotations/validation.json'
  # train_img_root: 'D:/Documents/Academic/workspace/python_prj/now/Steel_defect/dataset/NEU-DET_COCO/images'
  # val_img_root: 'D:/Documents/Academic/workspace/python_prj/now/Steel_defect/dataset/NEU-DET_COCO/images'
  
  train_annotation_path: '/content/gdrive/MyDrive/Colab Notebooks/Steel_defect/dataset/NEU-DET_COCO/annotations/train.json'
  val_annotation_path: '/content/gdrive/MyDrive/Colab Notebooks/Steel_defect/dataset/NEU-DET_COCO/annotations/validation.json'
  train_img_root: '/content/gdrive/MyDrive/Colab Notebooks/Steel_defect/dataset/NEU-DET_COCO/images'
  val_img_root: '/content/gdrive/MyDrive/Colab Notebooks/Steel_defect/dataset/NEU-DET_COCO/images'
  
  max_thresh: 320
  use_crowd: False
  batch_size: 128
  num_workers: 2
  debug: False
  remove_blank: Ture

model:
  num_cls: 6
  # https://github.com/martinzlocha/anchor-optimization/
  anchor_sizes: [32, 64, 128, 256, 512]
  anchor_scales: [0.934, 1.188, 1.49]
  anchor_ratios: [0.287, 1.0, 3.484]
  strides: [8, 16, 32, 64, 128]
  backbone: resnet18
  pretrained: True
  top_k: 9
  alpha: 0.4
  gamma: 0.9
  iou_type: giou
  iou_loss_weight: 1.0
  reg_loss_weight: 1.15
  iou_loss_type: centerness
  conf_thresh: 0.05
  nms_iou_thresh: 0.5
  max_det: 300

optim:
  optimizer: Adam
  lr: 0.0001
  milestones: [55]
  warm_up_epoch: 2
  weight_decay: 0.0001
  epochs: 60
  sync_bn: True
  amp: True
val:
  interval: 1
  weight_path: weights

resume:
  ckpt_name: ''

gpus: 0 # 0 or 'cpu'